# Generated by Django 4.0.6 on 2023-11-09 23:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        ('goals', '0003_alter_goal_created_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Release',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'created_at',
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ('start_at', models.DateTimeField()),
                ('end_at', models.DateTimeField()),
                ('release_name', models.CharField(max_length=255)),
                (
                    'description',
                    models.TextField(blank=True, max_length=512, null=True),
                ),
                (
                    'created_by',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'goal',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='goals.goal',
                    ),
                ),
                (
                    'product',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='organizations.product',
                    ),
                ),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
