# Generated by Django 4.0.6 on 2023-11-09 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('releases', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='release',
            table='releases',
        ),
    ]
