# Generated by Django 4.0.6 on 2026-07-09 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0013_organization_avatar_url_organization_github_org_id_and_more'),
        ('releases', '0002_alter_release_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='release',
            name='repositories',
            field=models.ManyToManyField(blank=True, related_name='releases', to='organizations.repository'),
        ),
    ]
