# Generated by Django 5.2.17 on 2026-09-27 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0013_organization_avatar_url_organization_github_org_id_and_more'),
        ('tsqmi', '0002_alter_tsqmi_options'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='tsqmi',
            index=models.Index(fields=['repository', '-created_at'], name='tsqmi_tsqmi_reposit_2e67e8_idx'),
        ),
    ]
