# Generated by Django 5.2.17 on 2026-09-27 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measures', '0001_initial'),
        ('organizations', '0013_organization_avatar_url_organization_github_org_id_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='calculatedmeasure',
            index=models.Index(fields=['repository', 'measure', '-created_at'], name='measures_ca_reposit_05eba1_idx'),
        ),
    ]
