sonar.projectKey=2026.1-MeasureSoftGram-Service
sonar.organization=fga-eps-mds-1

sonar.python.version=3.12

sonar.sources=src/
sonar.tests=src/
sonar.test.inclusions=src/**/tests.py,src/**/test_*.py,src/**/*_tests.py,src/**/tests/**

sonar.exclusions=src/utils/staticfiles/**,src/**/migrations/**,src/manage.py,src/config/settings/**,src/**/management/commands/seed_grafana.py
sonar.coverage.exclusions=src/**/management/commands/seed_grafana.py

sonar.python.coverage.reportPaths=coverage.xml
sonar.python.xunit.reportPath=junit.xml
