# Generated by Django 5.2.17 on 2026-09-27 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0013_organization_avatar_url_organization_github_org_id_and_more'),
        ('subcharacteristics', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='calculatedsubcharacteristic',
            index=models.Index(fields=['repository', 'subcharacteristic', '-created_at'], name='subcharacte_reposit_3ed3f1_idx'),
        ),
    ]
