apiVersion: 1

datasources:
  - name: MeasureSoftGram-DB
    type: grafana-postgresql-datasource
    uid: measuresoftgram-db
    access: proxy
    url: db:5432
    user: ${POSTGRES_USER}
    secureJsonData:
      password: ${POSTGRES_PASSWORD}
    jsonData:
      database: ${POSTGRES_DB}
      sslmode: disable
      maxOpenConns: 10
      maxIdleConns: 10
      connMaxLifetime: 14400
      postgresVersion: 1500
      timescaledb: false
    editable: false
    isDefault: true
