# Generated by Django 4.0.6 on 2022-07-16 16:11

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_measure'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectedMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SupportedMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=128, unique=True)),
                ('metric_type', models.CharField(choices=[('INT', 'Integer'), ('FLOAT', 'Float'), ('PERCENT', 'Percent'), ('BOOL', 'Boolean'), ('STRING', 'String'), ('DATA', 'Data'), ('LEVEL', 'Level'), ('MILLISEC', 'Milliseconds'), ('WORK_DUR', 'Work Duration'), ('DISTRIB', 'Distribution'), ('RATING', 'Rating')], max_length=15)),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True, max_length=512, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Measure',
        ),
        migrations.DeleteModel(
            name='Metric',
        ),
        migrations.AddField(
            model_name='collectedmetric',
            name='metric',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collected_metrics', to='service.supportedmetric'),
        ),
    ]
