# Generated by Django 4.0.6 on 2022-07-25 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0006_collectedmetric_path_collectedmetric_qualifier'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportedmeasure',
            name='metrics',
            field=models.ManyToManyField(blank=True, related_name='related_measures', to='service.supportedmetric'),
        ),
    ]
