# Generated by Django 4.0.6 on 2022-07-27 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0011_preconfig_supportedcharacteristic_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportedcharacteristic',
            name='subcharacteristics',
            field=models.ManyToManyField(blank=True, related_name='related_characteristics', to='service.supportedsubcharacteristic'),
        ),
        migrations.AddField(
            model_name='supportedsubcharacteristic',
            name='measures',
            field=models.ManyToManyField(blank=True, related_name='related_subcharacteristics', to='service.supportedmeasure'),
        ),
    ]
