# Generated by Django 4.0.6 on 2022-08-03 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0012_supportedcharacteristic_subcharacteristics_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectedmetric',
            name='dynamic_key',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
