# Generated by Django 4.0.6 on 2022-07-31 19:42

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0012_supportedcharacteristic_subcharacteristics_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalculatedSubCharacteristic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('subcharacteristic', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='calculated_subcharacteristics',
                    to='service.supportedsubcharacteristic'
                )),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
