# Generated by Django 4.0.6 on 2022-08-07 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0013_collectedmetric_dynamic_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supportedmetric',
            name='metric_type',
            field=models.CharField(choices=[('INT', 'Integer'), ('FLOAT', 'Float'), ('PERCENT', 'Percent'), ('BOOL', 'Boolean'), ('STRING', 'String'), ('DATA', 'Data'), ('LEVEL', 'Level'), ('MILLISEC', 'Milliseconds'), ('WORK_DUR', 'Work Duration'), ('DISTRIB', 'Distribution'), ('RATING', 'Rating')], default='FLOAT', max_length=15),
        ),
    ]
