# Generated by Django 4.0.6 on 2022-08-05 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0013_calculatedsubcharacteristic'),
        ('service', '0013_collectedmetric_dynamic_key'),
    ]

    operations = [
    ]
