# Generated by Django 4.0.6 on 2022-08-07 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0014_alter_supportedmetric_metric_type'),
        ('service', '0014_merge_20220805_1915'),
    ]

    operations = [
    ]
