# Generated by Django 4.0.6 on 2022-08-09 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0016_calculatedcharacteristic'),
        ('service', '0016_sqc'),
    ]

    operations = [
    ]
