# Generated by Django 4.0.6 on 2022-08-17 23:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0017_merge_0016_calculatedcharacteristic_0016_sqc'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('start_at', models.DateTimeField()),
                ('end_at', models.DateTimeField()),
                ('release_name', models.CharField(max_length=255)),
                ('data', models.JSONField()),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
