# Generated by Django 4.0.6 on 2022-08-22 22:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0019_organization_project_repository'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='repository',
            options={'verbose_name_plural': 'Repositories'},
        ),
        migrations.AddField(
            model_name='calculatedcharacteristic',
            name='repository',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='calculated_characteristics', to='service.repository'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='calculatedmeasure',
            name='repository',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='calculated_measures', to='service.repository'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='calculatedsubcharacteristic',
            name='repository',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='calculated_subcharacteristics', to='service.repository'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='collectedmetric',
            name='repository',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='calculated_metrics', to='service.repository'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='goal',
            name='repository',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='service.repository'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='preconfig',
            name='repository',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='pre_configs', to='service.repository'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sqc',
            name='repository',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='calculated_sqcs', to='service.repository'),
            preserve_default=False,
        ),
    ]
