# Generated by Django 4.0.6 on 2022-08-23 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0020_alter_repository_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Project',
            new_name='Product',
        ),
        migrations.RenameField(
            model_name='repository',
            old_name='project',
            new_name='product',
        ),
        migrations.AlterUniqueTogether(
            name='repository',
            unique_together={('name', 'product')},
        ),
    ]
