# Generated by Django 4.0.6 on 2022-08-25 14:33

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportedMetric',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('key', models.CharField(max_length=128, unique=True)),
                (
                    'metric_type',
                    models.CharField(
                        choices=[
                            ('INT', 'Integer'),
                            ('FLOAT', 'Float'),
                            ('PERCENT', 'Percent'),
                            ('BOOL', 'Boolean'),
                            ('STRING', 'String'),
                            ('DATA', 'Data'),
                            ('LEVEL', 'Level'),
                            ('MILLISEC', 'Milliseconds'),
                            ('WORK_DUR', 'Work Duration'),
                            ('DISTRIB', 'Distribution'),
                            ('RATING', 'Rating'),
                        ],
                        default='FLOAT',
                        max_length=15,
                    ),
                ),
                ('name', models.CharField(max_length=128)),
                (
                    'description',
                    models.TextField(blank=True, max_length=512, null=True),
                ),
            ],
            options={
                'ordering': ['key'],
            },
        ),
        migrations.CreateModel(
            name='CollectedMetric',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('value', models.FloatField()),
                (
                    'path',
                    models.CharField(
                        blank=True, default=None, max_length=255, null=True
                    ),
                ),
                (
                    'qualifier',
                    models.CharField(
                        blank=True, default=None, max_length=5, null=True
                    ),
                ),
                (
                    'dynamic_key',
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                (
                    'created_at',
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    'metric',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='collected_metrics',
                        to='metrics.supportedmetric',
                    ),
                ),
                (
                    'repository',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='calculated_metrics',
                        to='organizations.repository',
                    ),
                ),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
