# Generated by Django 5.2.17 on 2026-09-27 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0002_alter_collectedmetric_repository'),
        ('organizations', '0013_organization_avatar_url_organization_github_org_id_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='collectedmetric',
            index=models.Index(fields=['repository', 'metric', '-created_at'], name='metrics_col_reposit_e4f504_idx'),
        ),
    ]
