# Generated by Django 4.0.6 on 2022-08-22 19:28
from django.contrib.postgres.operations import CITextExtension
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        CITextExtension(),
    ]
