# Generated by Django 4.0.6 on 2026-06-12 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="github_access_token",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
