# Generated by Django 4.0.6 on 2022-08-26 21:03

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'created_at',
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ('start_at', models.DateTimeField()),
                ('end_at', models.DateTimeField()),
                ('release_name', models.CharField(max_length=255)),
                (
                    'created_by',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='accounts.customUser',
                    ),
                ),
                ('data', models.JSONField()),
                (
                    'product',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='goals',
                        to='organizations.product',
                    ),
                ),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
