# Generated by Django 4.0.6 on 2023-01-25 03:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('goals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='created_by',
            field=models.CharField(
                blank=True, default=False, max_length=255, null=True
            ),
        ),
    ]
