# Generated by Django 4.0.6 on 2023-11-14 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0003_alter_goal_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goal',
            name='end_at',
        ),
        migrations.RemoveField(
            model_name='goal',
            name='release_name',
        ),
        migrations.RemoveField(
            model_name='goal',
            name='start_at',
        ),
    ]
