# Generated by Django 4.0.6 on 2023-11-07 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_alter_repository_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='key',
            field=models.SlugField(blank=True, max_length=128, unique=True),
        ),
    ]
