# Generated by Django 4.0.6 on 2023-11-19 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0004_alter_organization_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repository',
            name='key',
            field=models.SlugField(blank=True, max_length=128),
        ),
    ]
