# Generated by Django 4.0.6 on 2023-11-11 18:08

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0007_alter_product_gaugeredlimit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='gaugeYellowLimit',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.66'), max_digits=3),
        ),
    ]
