# Generated by Django 4.0.6 on 2023-11-28 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0007_repository_platform'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='repository',
            unique_together={('name', 'key', 'product')},
        ),
    ]
