# Generated by Django 4.0.6 on 2023-12-09 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            'organizations',
            '0005_product_gaugeredlimit_product_gaugeyellowlimit',
        ),
        ('organizations', '0010_alter_repository_platform'),
    ]

    operations = []
