# Generated by Django 4.0.6 on 2024-09-04 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0011_merge_20231209_1347'),
    ]

    operations = [
        migrations.AddField(
            model_name='repository',
            name='imported',
            field=models.BooleanField(default=False),
        ),
    ]
