# Generated by Django 4.0.6 on 2022-08-25 23:10

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('name', models.CharField(blank=True, max_length=128, null=True)),
                ('data', models.JSONField()),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pre_configs', to='organizations.repository')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
