# Generated by Django 4.0.6 on 2022-08-27 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sqc', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sqc',
            options={'ordering': ['-created_at'], 'verbose_name': 'SQC', 'verbose_name_plural': 'SQC'},
        ),
    ]
