# Generated by Django 4.0.6 on 2023-12-09 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('releases', '0002_alter_release_table'),
        (
            'organizations',
            '0005_product_gaugeredlimit_product_gaugeyellowlimit',
        ),
        ('characteristics', '0003_calculatedcharacteristic_release'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='calculatedcharacteristic',
            unique_together={('repository', 'release')},
        ),
    ]
