# Generated by Django 5.2.17 on 2026-09-27 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characteristics', '0005_alter_calculatedcharacteristic_unique_together'),
        ('organizations', '0013_organization_avatar_url_organization_github_org_id_and_more'),
        ('releases', '0003_release_repositories'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='calculatedcharacteristic',
            index=models.Index(fields=['repository', 'characteristic', '-created_at'], name='characteris_reposit_21bc82_idx'),
        ),
    ]
